### ISSUE TITLE
Failing to scrape Argentine inflation data

### ISSUE THREAD

**Issue by dcorney** [FullFact/nso-stats-fetcher#11]
### Describe the bug

Collecting 'ar, cpi' data currently failing
(That's Argentina, consumer price index inflation)

This used to work, so it's probably the source that has changed (e.g. moved URL).
We have no paying customers using Argentinian data, so not urgent.

### To Reproduce

This is run as a series of cronjobs. See errors here:
https://github.com/FullFact/nso-stats-fetcher/actions

### Expected behaviour

No errors.

**Comment by andylolz** [comment]
I’ve just pushed a fix to improve the logging slightly, so we can see what’s going wrong. [Here’s the error that’s reported](https://github.com/FullFact/nso-stats-fetcher/actions/runs/5924997231/job/16063571750#step:7:18):

> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://apis.datos.gob.ar/series/api/series/?collapse=month&collapse_aggregation=avg&ids=148.3_INIVELNAL_DICI_M_26&limit=5000&representation_mode=percent_change_a_year_ago&format=json

Works for me locally, so I guess apis.datos.gob.ar is blocking based on IP address, something like that. It might be enough to change the user-agent, I don’t know, but would probably require a bit of fiddling about.

**Comment by dcorney** [comment]
Added the user agent; didn't fix the problem (so removed it again).

**Comment by andylolz** [comment]
Mm, kk.

We could proxy the requests, using proxy.fullfact.org… I suspect that would do the trick. I can send a PR?
